/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trabalho1;

import javax.swing.JOptionPane;

/**
 *
 * @author Jarvis
 */
public class Tranferencia extends javax.swing.JFrame {

    /**
     * Creates new form Tranferencia
     */
    public Tranferencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        num1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        num2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        valor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Transfêrencia");

        jLabel1.setText("Digite o numero da sua Conta:");

        jLabel2.setText("Digite o numero da outra Conta:");

        jLabel3.setText("Digite o valor para transfêrencia: ");

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(num1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(num2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(valor))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        CadastroContaNormal c1 = new CadastroContaNormal();
        CadastroContaPoupanca c2 = new CadastroContaPoupanca();
        CadastroContaEspecial c3 = new CadastroContaEspecial();
        
        Contas a1 = new Contas();
        ContaPoupanca a2 = new ContaPoupanca();
        ContaEspecial a3 = new ContaEspecial();
        
        String a = num1.getText();
        int num1 = Integer.parseInt(a);
        
        String b = num2.getText();
        int num2 = Integer.parseInt(b);
        
        String c = valor.getText();
        double valor = Double.parseDouble(c);
        
        if(num1 == c1.getEnviar()){
            if(num2 == c2.getEnviar()){
                boolean recebe = a1.transferir(num1, num2, valor);
                if (recebe == true){
                    JOptionPane.showMessageDialog(null,"Titular 1: " + c1.getEnviarNome() + "\nTitular 2: " + c2.getEnviarNome() + "\nTransferencia Efetuada com Sucesso!");
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null,"Saldo Insuficiente!");
                    this.dispose();
                }
                
            }
            if(num2 == c3.getEnviar()){
                boolean recebe = a1.transferir(num1, num2, valor);
                if(recebe == true){
                    JOptionPane.showMessageDialog(null,"Titular 1: " + c1.getEnviarNome() + "\nTitular 2: " + c3.getEnviarNome() + "\nTransfêrencia Efetuada com Sucesso!");
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null,"Saldo Insuficiente!");
                    this.dispose();
                }
            }
        }
        
        if(num1 == c2.getEnviar()){
            if(num2 == c1.getEnviar()){
                boolean recebe = a2.transferir(num1, num2, valor);
                if(recebe == true){
                    JOptionPane.showMessageDialog(null,"Titular 1: " + c2.getEnviarNome() + "\nTitular 2: " + c1.getEnviarNome() + "\nTransferência Efetuada com Sucesso!");
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null,"Saldo Insuficiente!");
                    this.dispose();
                }
            }
            if(num2 == c3.getEnviar()){
                boolean recebe = a2.transferir(num1, num2, valor);
                if(recebe == true){
                    JOptionPane.showMessageDialog(null,"Titular 1: " + c2.getEnviarNome() + "\nTitular 2: " + c3.getEnviarNome() + "\nTransfêrencia Efetuada com Sucesso!");
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null,"Saldo Insuficiente!");
                    this.dispose();
                }
            }
        }
        if(num1 == c3.getEnviar()){
            if(num2 == c1.getEnviar()){
                boolean recebe = a3.transferir(num1, num2, valor);
                if(recebe == true){
                    JOptionPane.showMessageDialog(null,"Titular 1: " + c3.getEnviarNome() + "\nTitular 2: " + c1.getEnviarNome() + "\nTransfêrencia Efetuada com Sucesso!");
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null,"Saldo Insuficiente!");
                    this.dispose();
                }
            }
            if(num2 == c2.getEnviar()){
                boolean recebe = a3.transferir(num1, num2, valor);
                if(recebe == true){
                    JOptionPane.showMessageDialog(null,"Titular 1: " + c3.getEnviarNome() + "\nTitular 2: " + c2.getEnviarNome() + "\nTransfêrebcia Efetuada com Sucesso!");
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null,"Saldo Insuficiente!");
                    this.dispose();
                }
            }
        }
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        JOptionPane.showMessageDialog(null,"Cancelado com Sucesso!");
        this.dispose();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tranferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tranferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tranferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tranferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tranferencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField num1;
    private javax.swing.JTextField num2;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
